version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend:/app
    environment:
      - FLASK_ENV=development
  frontend:
    build:
      context: ./src/frontend/oil-price-dashboard
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend/oil-price-dashboard:/app
    depends_on:
      - backend